name: CI/CD - Cloud Functions (Production)
on:
  push:
    paths:
      - '!.github/workflows/**'
      - server/**
    branches:
      - production

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Install Dependencies
        working-directory: ./server/functions
        run: npm install      
      - name: Deploy to Firebase
        run: ENVIRONMENT=production npm run deploy
        working-directory: ./server/functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
